# Generated by Django 3.2.8 on 2021-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='additional_ingredient',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='berry',
        ),
        migrations.AddField(
            model_name='cake',
            name='additional_ingredients',
            field=models.ManyToManyField(blank=True, related_name='cakes', to='cake.AdditionalIngredient', verbose_name='дополнительные ингредиенты'),
        ),
        migrations.AddField(
            model_name='cake',
            name='berries',
            field=models.ManyToManyField(blank=True, related_name='cakes', to='cake.Berry', verbose_name='ягоды'),
        ),
    ]
