# Generated by Django 3.2.8 on 2021-10-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_auto_20211028_1855'),
        ('cake', '0005_auto_20211029_2056'),
    ]

    operations = [
    ]
