# Generated by Django 3.2.8 on 2021-11-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_auto_20211030_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='наименование')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='значение')),
            ],
        ),
    ]
